apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: credit-scoring

resources:
  - ../../base

commonLabels:
  env: production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: scoring.company.io
    target:
      kind: Ingress
      name: main

images:
  - name: credit-scoring/backend
    newTag: v1.0.0
  - name: credit-scoring/frontend
    newTag: v1.0.0
